### ISSUE TITLE
Show current brightness and volume percentage near the slider.

### ISSUE THREAD

**Issue by arun54321** [Prayag2/kde_controlcentre#15]
![image](https://user-images.githubusercontent.com/42943340/194769623-a2431de8-6eb4-4369-b978-5a0794c3a161.png)

**Thanks**

**Comment by onuralpszr** [comment]
I did initial work able to add quickly 

![image](https://user-images.githubusercontent.com/1688848/194773914-fc151981-dd09-4fc7-bb8a-b79a0404c3ef.png)

Opening PR for this. @Prayag2  please assign to me. 

cc @Prayag2

**Comment by Prayag2** [comment]
Please don't open a PR right now. I have made a lot of changes in the code on my machine. Let me first commit the local changes.

**Comment by Prayag2** [comment]
@onuralpszr You can open it now.

**Comment by onuralpszr** [comment]
> @onuralpszr You can open it now.

Okay I see your changes, let me test with those and I will open it. 

Thank you.

**Comment by onuralpszr** [comment]
![image](https://user-images.githubusercontent.com/1688848/194774437-ebc8af2a-0f70-46bd-8d36-671f2899f6ae.png)

Looks nice to me :)

**Comment by arun54321** [comment]
It would be great if you make it optional. Because some people don't want to see percentage values for a cleaner look.

**Comment by Prayag2** [comment]
Done in https://github.com/Prayag2/kde_controlcentre/pull/31
