### ISSUE TITLE
Upcoming Changes for 0.1.0

### ISSUE THREAD

**Issue by Prayag2** [Prayag2/kde_controlcentre#17]
This is a list of all changes that will be coming in the next update. You can request for more by opening an issue.

## Features
- [x] Brightness controller
- [x] Ability to hide/show blocks of your choice
- [x] Ability to add custom buttons that run your own commands
- [x] An optional button that lets you switch to light/dark theme in an instant
- [x] Slider percentages
- [x] Add an option to customize the control centre icon.

## Fixes/Improvements
- [x] A different page for the "support me" section
- [x] Layout fixes
- [x] Refactor code to make it cleaner
- [x] Fix blurry icons and text

## Documentation
- [x] Better readme
- [x] A changelog
- [x] Contributing instructions

**Comment by Prayag2** [comment]
@onuralpszr Could you please check if the brightness slider is working? I refactored the code so I don't know if it still works or not.

**Comment by onuralpszr** [comment]
> @onuralpszr Could you please check if the brightness slider is working? I refactored the code so I don't know if it still works or not.

I saw tiny error and you also made 2 bool instead "one bool one int" If you check carefully. After I fix that I can see that brightness control but I couldn't read only variable inside of "PlasmaCore.DataSource" It was giving me error. So I take it out.

**Comment by onuralpszr** [comment]
@Prayag2 could you also add "create release" and "tag", plus remove that "archive file in repo and move into "release section" so we have don't have to download that tarball file as well (https://github.com/Prayag2/kde_controlcentre/tree/main/archives)

**Comment by Prayag2** [comment]
I'll create a release when all the things in this to-do list are complete.

**Comment by tuantran0910** [comment]
When will the new version be released Prayag2 ?

**Comment by Prayag2** [comment]
The new version has been released!
