### ISSUE TITLE
Add option to hide some elements

### ISSUE THREAD

**Issue by DenysMb** [Prayag2/kde_controlcentre#2]
Hi!
First of all, I wanna thank you and say that you did a very good job on this widget.
Second, I wanna propose one feature: to hide some elements from configuration.
For example, I don't use KDE Connect or the Night Color, so would be good to have an option on configuration to hide it.
The "main problem" would be to "organize" the others button when hiding some.
I think this would be easier if following the design of Gnome control center, with the fixed actions at the top and, on the bottom, all the options that could be hidden, with the same width and height, like in a "grid template".

**Comment by Prayag2** [comment]
Done in https://github.com/Prayag2/kde_controlcentre/pull/27
KDE Store version will be updated after the to-do #17 is completed.
