### ISSUE TITLE
[Feature request] WiFi on/off switch

### ISSUE THREAD

**Issue by LukasFoj** [Prayag2/kde_controlcentre#20]
It'd be good to be able to turn on/off wifi connection from panel. Also turned off devide (Wifi, bluetooth) could change icon color (turned on - color; turned off - black)

**Comment by onuralpszr** [comment]
@Prayag2 If you didn't start please assign to me. I am thinking of creating similar what KDE wifi menu has and once you press the button, It will be gray and It would be also nice to have "wifi settings" button as well.

**Comment by Prayag2** [comment]
Please only make changes in `Network.qml` or `SectionNetworks.qml` as I don't want to clutter `main.qml` and `FullRepresentation.qml`.

**Comment by Prayag2** [comment]
@onuralpszr Let's not add too many things at once for the next release. We can add it later because there are a lot of things to fix and add already..

**Comment by onuralpszr** [comment]
> @onuralpszr Let's not add too many things at once for the next release. We can add it later because there are already a lot of things to fix and add already..

Don't worry I will be gentle :). Plus I was just adding some features and fixes. Also I will follow new file structure you made, I just  bring functions, but sure I will keep clean.

**Comment by Prayag2** [comment]
Okay :)

**Comment by onuralpszr** [comment]
Hello, a little bit of update (I was little bit busy and I did more work and  figure out how to control wireless on/off properly and that is done, next part I am working on is main network menu and that is also almost done as well. 

Here is the sneak peak how is wifi switch looks like (when I turn off wifi I only see my vpns and bluetooth-devices for network so Wifi off actually work.) 

Update 2: I manage to change icon background Color based on plasma theme config (so we  going have new variable call sourceColor for set color situation like this) but now I have to check network setting for make sure "disconnected" completely and update text accordingly. 

Update 3: I talked with Plasma-NM developer for understand why is it show connected and my suspicious was virtual connections and indeed plasmaNM status reports "connected" I am going to open PR now but I am looking for handling virtual and local connections types for later on. 


![wifi_off](https://user-images.githubusercontent.com/1688848/195547388-5d7090c4-b862-4d49-b00b-4e525cfe27e1.png)

---

![wifi_on](https://user-images.githubusercontent.com/1688848/195547396-f08eaea4-7657-4d97-a06a-e7769d631a98.png)

---

![image](https://user-images.githubusercontent.com/1688848/195563288-9fa478d2-943a-49b2-860d-68602523a2a0.png)

**Comment by onuralpszr** [comment]
Last status and without virtual connection types (please see updates I wrote above) This is how is it looks If we turn off wifi and not connected to cable connection. 

![image](https://user-images.githubusercontent.com/1688848/195581931-55e69d74-f10d-4c87-bf90-9346fd8b21c5.png)
