### ISSUE TITLE
[FEATURE REQUEST] Add "Ding" Sound when changing volume in Control Centre

### ISSUE THREAD

**Issue by tuantran0910** [Prayag2/kde_controlcentre#32]
From my opinion, the "Ding" sound when changing volume can be a good idea to make the function more friendly to the user.

**Comment by Prayag2** [comment]
v0.1.0 is complete so I'll add this for v0.2.0 :)

**Comment by tuantran0910** [comment]
Thanks :)

**Comment by onuralpszr** [comment]
@Prayag2  would be okay to attach that sound effect into original kde notify sound settings (so we don't have to do custom sound selection)

**Comment by Prayag2** [comment]
@onuralpszr Yes that would be nice. I'm assigning this to you :D

**Comment by onuralpszr** [comment]
> @onuralpszr Yes that would be nice. I'm assigning this to you :D

oh right :)) looks like I have another task in my hand :)

**Comment by Prayag2** [comment]
Done in the latest commit :)
