### ISSUE TITLE
[Feature Request] Airplane mode (Disable/Enable wifi and bt) 

### ISSUE THREAD

**Issue by onuralpszr** [Prayag2/kde_controlcentre#34]
This will enable and disable bluetooth and wifi.

**Comment by Prayag2** [comment]
A button in the network section like the Wi-Fi one would be nice.

**Comment by onuralpszr** [comment]
> A button in the network section like the Wi-Fi one would be nice.

Yes, I can handle that please assign to me.

**Comment by onuralpszr** [comment]
Final look results (UI)

![image](https://user-images.githubusercontent.com/1688848/196550923-fe87c320-4f81-46a4-8205-0dbe8153aa4a.png)

![image](https://user-images.githubusercontent.com/1688848/196550967-43af4848-70d1-4da4-8f4b-c0be394acd7e.png)

**Comment by DenysMb** [comment]
I think it would be better if it have a little spacing between the wifi icon and the airplane checkbox. Like 8px or 4px.

**Comment by onuralpszr** [comment]
I added "Layout.rightMargin: root.smallSpacing" 

![image](https://user-images.githubusercontent.com/1688848/196636914-066ef49f-0e2b-413b-800c-685abd628c3b.png)

**Comment by Prayag2** [comment]
I've merged that pull request.
