### ISSUE TITLE
[Feature Request] A Better bluetooth menu (similar to wifi menu with on/off - add new device)

### ISSUE THREAD

**Issue by onuralpszr** [Prayag2/kde_controlcentre#35]
Similar to wifi menu with on/off and add new device button and trigger bluetooth add menu as well.

**Comment by Prayag2** [comment]
An similar issue is already open https://github.com/Prayag2/kde_controlcentre/issues/11

**Comment by onuralpszr** [comment]
> An similar issue is already open #11

Okay let's close this one and goes over there.
