### ISSUE TITLE
Won't work without pulseaudio?

### ISSUE THREAD

**Issue by acidrums4** [Prayag2/kde_controlcentre#36]
Using only alsa for audio management. Controlcentre will fail to launch:

```
file:///home/m/.local/share/plasma/plasmoids/com.github.prayag2.controlcentre/contents/ui/main.qml:62:34: Type FullRepresentation unavailable

file:///home/m/.local/share/plasma/plasmoids/com.github.prayag2.controlcentre/contents/ui/FullRepresentation.qml:89:13: Type Components.Volume unavailable

file:///home/m/.local/share/plasma/plasmoids/com.github.prayag2.controlcentre/contents/ui/components/Volume.qml:6:1: module "org.kde.plasma.private.volume" is not installed
```

I can't be the only one not using pulseaudio. It would be cool if there was something to detect wether running/having pulseaudio (be it programatically or an user option) so it will try to load the audio widget only if pulseaudio is found, and else (and if possible) to run an alsa-based widget or not include it at all.

**Comment by onuralpszr** [comment]
Hello;

I am using "pipewire" not "pulseaudio and It does work and secondly you just need to install "plasma-pa" package based on your linux distro (for example for fedora you just need to install "dnf install plasma-pa" and It will work. (tested as well)

**Comment by acidrums4** [comment]
> I am using "pipewire" not "pulseaudio

Pipewire still depends on pulseaudio, so... pulseaudio.

> you just need to install "plasma-pa" package based on your linux distro

plasma-pa precisely is the plasma wrapper for pulseaudio.

It would be nice it was mentioned in the dependencies section, at least.
