### ISSUE TITLE
[FEATURE REQUEST] Is there anyway to contribute for add another language?

### ISSUE THREAD

**Issue by ghost** [Prayag2/kde_controlcentre#45]
**I have my whole system on spanish, this widget is amazing, but feels pretty much out of place!**
I know pretty much all the simple english stuff, so i will love to contribute adding a spanish language option to the widget, so in the future we can also have more languages for the widget, that will be absoluty awesome!

**Comment by Prayag2** [comment]
Duplicate of https://github.com/Prayag2/kde_controlcentre/issues/10.
Translations are coming in the next update :)
