### ISSUE TITLE
[FEATURE REQUEST] How Can I Apply To Gnome??

### ISSUE THREAD

**Issue by DixitRam** [Prayag2/kde_controlcentre#46]
Is There Any Way To Apply This Theme To My Gnome 40!!!

**Comment by Prayag2** [comment]
You can try using Latte Dock but there's no guarantee that it will work.

**Comment by DixitRam** [comment]
Will it able  to get your theme

**Comment by roke-julian-lockhart** [comment]
@Dixit-deegit, just try it.
