### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by lsomm** [Prayag2/kde_controlcentre#6]
I downloaded the widget and when i tried to drag it to my Desktop, it threw me this error

```
file:///home//.local/share/plasma/plasmoids/com.github.prayag2.controlcentre/contents/ui/main.qml:31:34: Type FullRepresentation unavailable

file:///home/myusername/.local/share/plasma/plasmoids/com.github.prayag2.controlcentre/contents/ui/FullRepresentation.qml:15:1: module "org.kde.plasma.private.nightcolorcontrol" is not installed

file:///home/myusername/.local/share/plasma/plasmoids/com.github.prayag2.controlcentre/contents/ui/FullRepresentation.qml:10:1: module "org.kde.plasma.private.bluetooth" is not installed

file:///home/myusername/.local/share/plasma/plasmoids/com.github.prayag2.controlcentre/contents/ui/FullRepresentation.qml:15:1: module "org.kde.plasma.private.nightcolorcontrol" is not installed

file:///home/myusername/.local/share/plasma/plasmoids/com.github.prayag2.controlcentre/contents/ui/FullRepresentation.qml:10:1: module "org.kde.plasma.private.bluetooth" is not installed
```

My PC does not support Bluetooth and I uninstalled the KDE tools for it. It would be nice if having this installed is not a requirement.

I do have the Plasma NightColor thingy installed and use it. SO I dont know why it is not recognised.

(Maybe my PC is just cursed, but its a fairly standard Fedora setup, so i think many would/could profit.)

If you have any questions, hit me up!

Specs:

`Operating System: Fedora Linux 36
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.6
Kernel Version: 5.19.13-200.fc36.x86_64 (64-bit)
Graphics Platform: Wayland
`

**Comment by ghost** [comment]
Can confirm similar error here:

```
file:///home/user/.local/share/plasma/plasmoids/com.github.prayag2.controlcentre/contents/ui/main.qml:31:34: Type FullRepresentation unavailable

file:///home/user/.local/share/plasma/plasmoids/com.github.prayag2.controlcentre/contents/ui/FullRepresentation.qml:15:1: module "org.kde.plasma.private.nightcolorcontrol" is not installed
```

OS: Arch Linux
Plasma: 5.25.5
Frameworks: 5.98.0
Compositor: Wayland

**Comment by marcdeop** [comment]
On my Fedora 36 I had to install:
* kdeplasma-addons
* plasma-nm

**And** trigger a plasma reload with `plasmashell --replace`

**Comment by Prayag2** [comment]
The applet has a lot of different functionalities. It's not possible to make some dependencies optional at the moment (it's hard and I have exams). I'll keep this issue open for the time being.
To use it, you need to install `kdeplasma-addons` and `plasma-nm`.

**Comment by lsomm** [comment]
That is very respectable. You rock ! Good luck w/ the exams :)

**Comment by claymorwan** [comment]
> The applet has a lot of different functionalities. It's not possible to make some dependencies optional at the moment (it's hard and I have exams). I'll keep this issue open for the time being. To use it, you need to install `kdeplasma-addons` and `plasma-nm`.

I have both these pkg installed but it's not working :c
