### ISSUE TITLE
[BUG] Plasma 6 Support

### ISSUE THREAD

**Issue by zany130** [Prayag2/kde_controlcentre#61]
**Describe the bug**
Plasmoid does not work on plasma 6

**To Reproduce**
1. Install on plasma 6

**Expected behavior**
Works on plasma 6

**Desktop (please complete the following information):**
Operating System: Garuda Linux 
KDE Plasma Version: 6.0.0
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.7.6-1-cachyos (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6700 XT

**Have you installed the following dependencies? (Yes/No)**
 - `kdeplasma-addons`: Yes 
 - `plasma-nm`: Yes
 - KDE Connect Yes

**Additional context**
https://develop.kde.org/docs/plasma/widget/porting_kf6/

**Comment by SadColourfulHues** [comment]
It's still a WIP, but I've got most of Control Centre ported to Plasma 6. 
I'll open a PR once the remaining tasks have been completed.

https://github.com/SadColourfulHues/kde_controlcentre_plasma6/tree/develop
