### ISSUE TITLE
[BUG] Plasma 6.1 Support

### ISSUE THREAD

**Issue by refurbishing** [Prayag2/kde_controlcentre#64]
**Describe the bug**
It says ''Sorry! There was a error loading Control Centre''

```
file:///home/cortex/.local/share/plasma/plasmoids/com.github.boraerciyas.controlcentre/contents/ui/main.qml:67:25: Type FullRepresentation unavailable
file:///home/cortex/.local/share/plasma/plasmoids/com.github.boraerciyas.controlcentre/contents/ui/FullRepresentation.qml:75:21: Type Components.RedShift unavailable
file:///home/cortex/.local/share/plasma/plasmoids/com.github.boraerciyas.controlcentre/contents/ui/components/RedShift.qml:64:5: NightColorInhibitor is not a type
```

**To Reproduce**
1. Open it.
2. See the error.

**Expected behavior**
To work correctly, on the new plasma version.

**Screenshots**
![image](https://github.com/Prayag2/kde_controlcentre/assets/126973723/b7f63203-26f0-466d-8c1d-924ce4e82e28)

**Desktop (please complete the following information):**
 - KDE Plasma Version: 6.1.0
 - Distribution: EndeavourOS x86_64
 - Qt Version: 6.7.1
 - KDE Frameworks Version: 6.3

**Have you installed the following dependencies? (Yes/No)**
 - `kdeplasma-addons`: Yes 
 - `plasma-nm`: Yes
 - KDE Connect: Yes

**Additional context**

**Comment by SadColourfulHues** [comment]
Plasma 6.1 seems to have changed the way to inhibit their night light control again. Fortunately, that seems to be the only issue that prevents the widget from starting. I've already made a PR (#65) to merge the fix here. 

If you want to, you can install the updated version by cloning this [repo](https://github.com/SadColourfulHues/kde_controlcentre_plasma6/tree/plasma6.1), and running `plasmapkg2 -u package/` in the root project dir.

**Comment by refurbishing** [comment]
> Plasma 6.1 seems to have changed the way to inhibit their night light control again. Fortunately, that seems to be the only issue that prevents the widget from starting. I've already made a PR (#65) to merge the fix here.
> 
> If you want to, you can install the updated version by cloning this [repo](https://github.com/SadColourfulHues/kde_controlcentre_plasma6/tree/plasma6.1), and running `plasmapkg2 -u package/` in the root project dir.

Thanks. It worked great, but i noticed that the audio setting was removed, there's no internet connection status.

![image](https://github.com/Prayag2/kde_controlcentre/assets/126973723/c8d05d56-669b-446f-b841-014baab9f6a3)

Here's a log of may be the error causing this:
```
error getting max keyboard brightness via dbus QDBusError("org.freedesktop.DBus.Error.UnknownObject", "No such object path '/org/kde/Solid/PowerManagement/Actions/KeyboardBrightnessControl'")
file:///home/cortex/.local/share/plasma/plasmoids/com.github.prayag2.controlcentre/contents/ui/FullRepresentation.qml:75:21: QML RedShift: Binding loop detected for property "inhibitor"
qml: pass
file:///home/cortex/.local/share/plasma/plasmoids/com.github.prayag2.controlcentre/contents/ui/components/SectionButtons.qml:39: ReferenceError: Kirigami is not defined
file:///home/cortex/.local/share/plasma/plasmoids/com.github.prayag2.controlcentre/contents/ui/components/SectionButtons.qml:36:13: Unable to assign [undefined] to QString
file:///home/cortex/.local/share/plasma/plasmoids/com.github.prayag2.controlcentre/contents/ui/components/RedShift.qml:16: ReferenceError: redMonitor is not defined
file:///home/cortex/.local/share/plasma/plasmoids/com.github.prayag2.controlcentre/contents/ui/lib/Slider.qml:87:17: Unable to assign [undefined] to QQuickSlider::SnapMode
file:///home/cortex/.local/share/plasma/plasmoids/com.github.prayag2.controlcentre/contents/ui/components/Volume.qml:34: TypeError: Cannot read property 'volume' of undefined
file:///home/cortex/.local/share/plasma/plasmoids/com.github.prayag2.controlcentre/contents/ui/components/Volume.qml:25:5: Unable to assign [undefined] to bool
file:///home/cortex/.local/share/plasma/plasmoids/com.github.prayag2.controlcentre/contents/ui/components/Volume.qml:31: TypeError: Cannot read property 'volume' of undefined
file:///home/cortex/.local/share/plasma/plasmoids/com.github.prayag2.controlcentre/contents/ui/components/Volume.qml:30: TypeError: Cannot read property 'volume' of undefined
file:///home/cortex/.local/share/plasma/plasmoids/com.github.prayag2.controlcentre/contents/ui/lib/Slider.qml:87:17: Unable to assign [undefined] to QQuickSlider::SnapMode
QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0
```

**Comment by SadColourfulHues** [comment]
Apologies, I typically don't have the volume and media sections enabled on my end. Anyways, the new commits should resolve both the network label and volume slider issues.

![Screenshot_20240621_220231](https://github.com/Prayag2/kde_controlcentre/assets/46611929/08807d78-6f0c-4706-8b50-2a61f2bd4f66)

**Comment by refurbishing** [comment]
> Apologies, I typically don't have the volume and media sections enabled on my end. Anyways, the new commits should resolve both the network label and volume slider issues.
> 
> ![Screenshot_20240621_220231](https://private-user-images.githubusercontent.com/46611929/341789009-08807d78-6f0c-4706-8b50-2a61f2bd4f66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5ODA0MjMsIm5iZiI6MTcxODk4MDEyMywicGF0aCI6Ii80NjYxMTkyOS8zNDE3ODkwMDktMDg4MDdkNzgtNmYwYy00NzA2LThiNTAtMmE2MWYyYmQ0ZjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDE0Mjg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMTQ0NGVkZWE5NTIwMWE1YjRkNjA2ZmExYmEwNzY3ZWM0YTkwYjI1YTIyMjczZWJiZjRhMzY2MzIyMWQxNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6m5g8UVWRPMTMmtxIlbMqLGk8ZBqkyBkG7KqpXjCm7M)

It Worked Perfectly, Thank you.

**Comment by Alexandre-BARBIER** [comment]
Hello, will it be added to the Plamsa 6 widget store ?

**Comment by benmordecai** [comment]
If this is fixed now can we get it pushed to the Plasma Store?

**Comment by refurbishing** [comment]
> If this is fixed now can we get it pushed to the Plasma Store?

The Repo Owner has to merge the PR for that to happen

**Comment by benmordecai** [comment]
@Prayag2

**Comment by ghost** [comment]
> Apologies, I typically don't have the volume and media sections enabled on my end. Anyways, the new commits should resolve both the network label and volume slider issues.

@SadColourfulHues Why don't you publish the fork on kde-store , if the license allows

**Comment by Prayag2** [comment]
I'm sorry everyone. I'm not really getting the time to manage my open source projects. I recommend you all to check out https://github.com/zayronxio/Plasma-Control-Hub
It's actively maintained and has better features!
