### ISSUE TITLE
[Feature Request] Allow adding custom command buttons or replace existing buttons

### ISSUE THREAD

**Issue by casualsnek** [Prayag2/kde_controlcentre#9]
For example the kde connect button is not too useful for me, so i want to add a toggle script to change my theme in it's place, if possible can you make buttons configurable or replaceable.

Example implementation of custom command button widget: https://www.pling.com/p/1297839
If would be nice to have a button with 2 state and runs command just like this and changes it's icon to the icon for just run command ( Button state is saved across sessions ) !

**Comment by Prayag2** [comment]
Done in https://github.com/Prayag2/kde_controlcentre/pull/30
Will be available in the KDE store in the next update (0.1.0).
